authorName: default
experimentName: usa_real_estate_nni
trialConcurrency: 1
maxExecDuration: 10000000000h
maxTrialNum: 10
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: search_space_usa.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: Evolution 
  classArgs:
    optimize_mode: 'minimize'
    population_size : 50
    #choice: maximize, minimize
    #optimize_mode: maximize

trial:
  command: python usa_real_estate_nni.py
  codeDir: .
  gpuNum: 0
